### PR TITLE
CORENTIN_ALBERTUS_STRCMP_FIX

### PR DESCRIPTION
**Pull request by messtt**
0 if the s1 and s2 are equal | -1 negative value if s1 is less than s2 | 1 positive value if s1 is greater than s2.

### CODE REVIEW

**Review by alexis-belmonte — CHANGES_REQUESTED** [review]
The `.idea` folder should've not been commited as the files contained inside of it are pretty much unique to your setup :frowning:

**Review by pulk66-s — CHANGES_REQUESTED** [review]
src/utils/string/strcmp.c
```c
int strcmp(char *s1, char *s2)
{
    int len_s1 = strlen(s1);
    for (int i = 0; i < len_s1; i++) {
        if (s1[1] > s2[i])
            return 1;
        if (s1[1] < s2[i])
            return -1;
    }
    return 0;
}
```
Things to change:
- args must be const
- Do not use strlen... You have the '\0'
- Do not use `int` in for loop use `size_t` instead 

src/utils/string/strcmp.h
Things to change:
- The header must be sticked to the function prototype
- The header must have no tabs
- The header must be in this form:
```c
* @return 0: ...
* @return 1: ...
* @return -1: ...
```
- Do not have space between pointer and their variables `char * s1` -> ` char *s1`

**Review by theobori — COMMENTED** [review]
+ you should test your code, some cases are not working

**Review by theobori — COMMENTED** [review]
It is still not working + some cases are crashing 💀

**Review by theobori — CHANGES_REQUESTED** [review]
- Remove the .idea folder.

Not working case examples:
- my_strcmp("", "aa" )
- my_strcmp("aadd", NULL )
- my_strcmp("12", "121" )

**Review by pulk66-s — CHANGES_REQUESTED** [review]
- Do not include useless lib (strlen.h)
- Change the return type (-1 cannot be a size_t)
- Explain in your header why you return 84
- Place parentheses when you have multiples conditions:
- The condition in the loop are useless, you only need to compare the two char and not the '\0' char. It's making the program slower. You can move it after the while statement
- Put a tab when you include a .h in another .h, like this
```c
#ifndef HEADER
    #define HEADER
    
    #include "types.h"

// ...
```

**Review by pulk66-s — COMMENTED** [review]
Also,
- Delete the .idea/*
- Why your file is not in the Makefile ??

**Review by pulk66-s — CHANGES_REQUESTED** [review]
- Do not compile
- still .idea

**Review by pulk66-s — CHANGES_REQUESTED** [review]
in src/utils/string/strcmp.c:
Useless conditions:
```c
if (*s1 > *s2)
    return *s1 - *s2;
if (*s1 < *s2)
    return *s1 - *s2;
```
can be change by
```c
if (*s1 != *s2)
    return *s1 - *s2;
```

Different prototype between strcmp.c and strcmp.h

**Pull request closed without merging**
